palette:
  top: '#055a8e'
  bottom: '#3e3e3e'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#0071b3'
logo: 'public://color/bartik-77413f2e/logo.svg'
stylesheets:
  - 'public://color/bartik-77413f2e/colors.css'
files:
  - 'public://color/bartik-77413f2e/logo.svg'
  - 'public://color/bartik-77413f2e/colors.css'
